"""Package the complete beta addon and installation notes; no game client needed."""
import argparse
import hashlib
import json
import re
import sys
import zipfile
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--output', type=Path, default=Path('/workspace/artifacts'))
    parser.add_argument('--post-discord', action='store_true', help='Post the verified release and its matching changelog/test checklist.')
    args = parser.parse_args()
    addon = ROOT / 'WowTogether'
    coverage = json.loads((addon / 'QuestCatalogue.json').read_text())
    toc = (addon / 'WowTogether.toc').read_text()
    if not re.search(r'^## Interface: 16001$', toc, re.M):
        raise ValueError('Release must target Forever interface 16001')
    version = re.search(r'^## Version: ([0-9]+\.[0-9]+\.[0-9]+)$', toc, re.M).group(1)
    names = [line.strip() for line in toc.splitlines() if line.strip() and not line.startswith('#')]
    for name in names:
        if not re.fullmatch(r'[A-Za-z0-9_]+\.lua', name):
            raise ValueError('Unexpected addon source path: ' + name)
        if not (addon / name).read_text().startswith('local addonName, ns = ...\n'):
            raise ValueError('Missing namespace declaration: ' + name)
    instructions = f'''Wow Together {version} — Forever beta

Copy the complete WowTogether folder to:
World of Warcraft\\_classic_beta_\\Interface\\AddOns\\WowTogether\\

Update EVERY party member to {version}, including ALL {len(names)} Lua files,
then /reload. Restart the client fully if a new addon folder does not appear.
No Battle.net credentials or external API service are needed.

/wt opens the Classic-style resizable dashboard. Its dropdown has Leveling guides,
All quests (formerly Library), Party quests, Shared, Party progress, Dungeon quests,
Profession guides and Quest log review. All quests searches commit on Enter or pause.
Use level brackets / Near party to narrow the list.
Leveling guides has its own bracket dropdown, deferred zone/quest/NPC search
and pages. The default bracket follows the lowest party level. Only full zone
guides and published questlines appear; explicit quest-log trips are in Party quests.
Brackets filter browsing; a selected guide keeps later levels and known cross-zone
steps. Fixed zone guides are ON by default. Loading route appears while the complete
catalogue sequence is compiled once, independently of location and quest logs.
Progress advances without changing that order, including after abandon or Scan.
Turn Follow fixed zone guides off and restart a guide for adaptive trips, which
hold up to six quests/twenty stops; their full preview is not limited to that trip.
Optional suitable next-zone prompts offer Start zone guide / Keep my guide.
/wt config has purpose-based settings pages with dropdowns and help text.
/wt tracker toggles the movable, scrollable party panel; it opens when joining a
normal party and hides when solo/in a raid. Closing it lasts for that party session.
/wt arrow toggles the movable direction panel. Choose yards or metres in settings.
/wt sync requests fresh snapshots; normal quest/party changes sync automatically.
/wt probe opens diagnostics; Ctrl+C copies and closes the report.
/wt research opens local quest-data JSON; Select all, Ctrl+C, then save as a text
file labeled with your tester name for feedback. Settings → Quest data for testing
has the recording toggle and Export quest data. The latest 300 local observations
persist per character: actual NPC offers, acceptance/hand-in, build and relevant
history/context and manual skips. Skips never imply an unlock or missing offer.
Visit the same NPC before/after a hand-in. Exports omit character
names/chat and are never uploaded automatically.
One clean full-list/one-hand-in/new-offer pair can create a tentative prerequisite.
Use observed prerequisite patterns controls reuse on this account, matched by
build/faction for ordinary quests, across classes and races. Class/race-specific
quests or prerequisites keep that dimension restricted. Existing findings migrate;
contradictory merged predecessors remain disabled for review.
Changed level means review-only; published alternatives
are never narrowed and live contradictions disable a learned pattern. Influenced
steps credit the source. No existing fixed sequence is regenerated by learning.
/wt findings or Export guide findings includes account-wide patterns and proofs.
Include source names in guide findings is optional, OFF by default. Send labeled
files for review to improve the bundled guides; no automatic upload or sync.
/wt questlines inspects native questline fields and optional GetQuestLineQuests IDs
in a copyable window. This is a capability test, not a prerequisite contract.
The Hunt Continues (750) requires handing in The Hunt Begins (747), from a tester
report preserved separately from published source facts. Restart the Mulgore guide
after upgrading to compile the corrected sequence.
/wt route clear clears the map route. /wt minimap toggles its dashboard button.

Show route is local. Start route invites friends with Follow route / Keep my route.
Fixed zone guides start directly and keep their generic order. Adaptive guides
with current quests offer Start selected guide or Include current quests, with
a warning about detours. Explicit quest-log routes remain
selectable in Party quests. Quest acceptance/zone updates retain the selection.
Full zone/questline invitations share guide identity and bracket, allowing friends
to reconstruct the full catalogue scope beyond the twenty transmitted quest IDs.
Low-level pickups need a known useful later quest/dungeon exception, explained
under the arrow. Party stages focus on the member behind in confirmed progress.
Unknown prerequisites/history stay unknown. Active work you choose can remain.

Left/right arrow buttons preview previous/later steps without changing quest credit.
History previews use published locations, not a recorded travel timeline.
Skip step / Skip quest persist for this character and do not change friends' credit.
Scan guide reads real progress without changing fixed order; adaptive mode replans.
The extra Guide replanned footer is removed. Diagnostics distinguish the full
guide's quest scope from its current trip's quests and map stop counts.
Reconsider skips when scanning is off by default; on clears selected-guide quest skips.
Reset guide skips or /wt guide reset restores ALL guides' skips for this character.
/wt guide scan performs the same progress refresh from the command line.

Map lines show the current place plus two ahead, or use Show full route for ALL
currently eligible mapped quests. Locked future quests remain in the sequence.
Coverage counts distinguish known quest facts from actual map coordinates.
Shared NPC steps stay grouped. View route zone opens the current destination map.
Lines use world-map visiting order only; they do not follow roads or draw on the minimap.
The addon no longer sets extra Blizzard waypoint pins. Numbered route markers
and the arrow remain; unrelated manual waypoints are untouched. Clear older pins
manually if one remains from a previous version.
Follow roads/terrain. Pan/zoom redraws verified unprotected addon geometry in combat;
protected frames and native map actions wait. Actual beta rendering needs testing.

Open flight-master maps to learn this character's network. Useful known flights
compare estimated walk/flight/walk costs; timed rides improve their duration.
Nearby observed unconfirmed paths may get a short check stop. There is no complete
flight-path database. Select the suggested flight is optional and OFF by default;
only the open matching source's public reachable slot is requested outside combat.
While flying, elapsed/approximate remaining time replaces distance. As a ghost,
corpse directions temporarily replace the guide; missing corpse data is explicit.

Kill / Pick up / Talk instructions name known targets. Cross markers (or optional
kill skulls) and quest-item tooltip hints require public data and hide in combat.
Finished objective types lose hints unless another unfinished quest/member needs them.
NPC gossip and quest-greeting lists can confirm/block offers in the current progress context; a single dialog
confirms that quest only. Every pickup checks known prerequisites before positive
NPC evidence. Accepting, objective completion or skipping is not a prerequisite
hand-in. Unknown history stays unknown. Actual offers can confirm missing source
requirements but cannot bypass known unfinished chains or identity/level restrictions.
IsPushableQuest is sharing only; IsQuestCompletable is opened-dialog turn-in only.
Neither is a pickup gate. The old beta setting/packets are removed.
Normal event sync rechecks progress; locked quests stay in the full guide and
accepted work remains. Diagnostics show per-quest reasons and NPC evidence.
Published-data candidates can still have hidden beta gates; visit the NPC to verify.
Quest-dialog selection, auto-accept and no-choice auto-turn-in are separate opt-ins,
all OFF by default. Reward choices stay manual. Presence/attempts do not prove beta
protected-action behavior. New flight, gossip, item-hook and corpse APIs need testing.
Quest greeting probes must also be retested on Forever. Missing fields cannot
prove absence, and unpublished prerequisites are not guessed from quest IDs.

Dungeon Start route collects known eligible pickups then a nearby located entrance.
Missing prerequisites/coordinates remain explicit; Record entrance here is available.
Quest log review only suggests reviewing low-value unfinished work; it never abandons.
Personal professions use your opened recipes/materials, configurable small batches,
and AH searches YOU perform. No automatic buying, searching or crafting.
Profession/flight/skip state is not sent to peers.

The partial snapshot has {coverage['count']:,} quest records and
{coverage['detailed_quests']:,} detailed pages; most objective coordinates are missing.
Known repeatables remain excluded from automatic leveling. Live offers/history
are authoritative; published facts can differ from the beta.

Read README.md for full behavior and limits, CHANGELOG.md for this release,
and TESTING.md for the labeled friend-testing checklist. Host checks alone do not
establish actual WoW Forever API, protected-action or rendering compatibility.
'''
    args.output.mkdir(parents=True, exist_ok=True)
    destination = args.output / f'WowTogether-{version}.zip'
    files = ['WowTogether.toc', *names, 'QuestCatalogue.json']
    with zipfile.ZipFile(destination, 'w', zipfile.ZIP_DEFLATED) as archive:
        for name in files:
            archive.write(addon / name, 'WowTogether/' + name)
        for name in ('README.md', 'TESTING.md', 'CHANGELOG.md'):
            archive.write(ROOT / name, 'WowTogether/' + name)
        archive.write(ROOT / 'LICENSE', 'WowTogether/LICENSE')
        archive.writestr('WowTogether/INSTALL.md', instructions)
    with zipfile.ZipFile(destination) as archive:
        if archive.testzip() is not None:
            raise ValueError('Release archive failed verification')
    print(f'{destination}: {len(names)} Lua files, {destination.stat().st_size} bytes')
    print('SHA256 ' + hashlib.sha256(destination.read_bytes()).hexdigest())
    if args.post_discord:
        from post_discord_release import PublicationError, configured_webhook, post_release
        try:
            post_release(destination, configured_webhook())
        except (PublicationError, ValueError) as error:
            print(str(error), file=sys.stderr)
            raise SystemExit(1) from None


if __name__ == '__main__':
    main()
