"""Generate an offline Forever quest catalogue from Warcraft DB's public JSON.

Only quest facts are included; no descriptions, artwork, or addon source code.
Missing source fields stay unknown. NPC positions are not inferred from prose.
"""
import argparse
import concurrent.futures
import datetime
import json
import re
import time
import urllib.error
import urllib.request
from pathlib import Path

BASE = 'https://forever.warcraftdb.com'
ROOT = Path(__file__).resolve().parents[1]


def number(value, maximum=2147483647):
    return value if type(value) is int and 0 <= value <= maximum else None


def clean(value):
    return re.sub(r'[\x00-\x1f\x7f|]', ' ', value).strip() if isinstance(value, str) else ''


def normalize(row, detail):
    data = detail.get('data', {})
    result = {'title': clean(data.get('name') or row.get('name')),
              'zone': clean(data.get('zone') or row.get('zone'))}
    for source, target, maximum in [('level', 'level', 255), ('min_level', 'minLevel', 255),
                                    ('zone_id', 'mapID', 1000000), ('suggested_group', 'suggestedGroup', 40)]:
        value = number(data.get(source, row.get(source)), maximum)
        if value is not None:
            result[target] = value
    side = data.get('side')
    if side in ('Horde', 'Alliance', 'Both', 'Neutral'):
        result['side'] = side
    quest_type = clean(data.get('quest_type') or row.get('quest_type'))
    if quest_type:
        result['questType'] = quest_type
    rewards = data.get('rewards', {})
    if isinstance(rewards, dict):
        xp = number(rewards.get('xp'))
        if xp is not None:
            result['xp'] = xp
    tags = clean(data.get('tags'))
    if 'Sharable' in tags:
        result['shareable'] = True
    # The catalogue does not assume that absent faction/prerequisite/giver data
    # means no restrictions, or invent a chain from neighboring quest IDs.
    return result


def lua_value(value):
    if type(value) is bool:
        return 'true' if value else 'false'
    if type(value) in (int, float):
        return str(value)
    if isinstance(value, list):
        return '{' + ', '.join(lua_value(v) for v in value) + '}'
    if isinstance(value, dict):
        return '{' + ', '.join(f'{k} = {lua_value(v)}' for k, v in sorted(value.items())) + '}'
    return json.dumps(value, ensure_ascii=False)


def generate(records, date):
    lines = ['local addonName, ns = ...', '',
             '-- Generated by tools/import_warcraftdb.py; public quest facts only.',
             '-- Unknown requirements and locations are deliberately omitted.',
             'ns.catalogue = {',
             f'    source = "{BASE}/list/quests",',
             f'    captured = "{date}",',
             f'    count = {len(records)},',
             '    quests = {']
    for quest_id, record in sorted(records.items()):
        fields = ', '.join(f'{key} = {lua_value(value)}' for key, value in sorted(record.items()))
        lines.append(f'        [{quest_id}] = {{{fields}}},')
    lines += ['    },', '}', '']
    return '\n'.join(lines)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--cache', type=Path, default=Path('/tmp/wow-together-warcraftdb'))
    parser.add_argument('--output', type=Path, default=ROOT / 'WowTogether' / 'QuestCatalogue.lua')
    parser.add_argument('--refresh', action='store_true')
    args = parser.parse_args()
    args.cache.mkdir(parents=True, exist_ok=True)

    def fetch(path, key, paced=False):
        cache = args.cache / (key + '.json')
        if cache.exists() and not args.refresh:
            return json.loads(cache.read_text())
        if paced:
            time.sleep(0.25)
        for attempt in range(3):
            try:
                request = urllib.request.Request(BASE + path, headers={'User-Agent': 'WowTogether-catalogue-import/0.3'})
                with urllib.request.urlopen(request, timeout=25) as response:
                    data = json.load(response)
                cache.write_text(json.dumps(data, ensure_ascii=False))
                return data
            except urllib.error.HTTPError as error:
                if error.code not in (429, 500, 502, 503, 504) or attempt == 2:
                    raise
                time.sleep(min(20, int(error.headers.get('Retry-After', '2')) * (attempt + 1)))
        raise RuntimeError('Fetch did not complete')

    first = fetch('/api/data/list/quests?page=1&per_page=100', 'list-1')
    total = number(first.get('total'), 10000)
    pages = number(first.get('pages'), 1000)
    if total is None or not pages:
        raise RuntimeError('Unexpected catalogue pagination')
    rows = list(first['rows'])
    for page in range(2, pages + 1):
        rows += fetch(f'/api/data/list/quests?page={page}&per_page=100', f'list-{page}', True)['rows']
    ids = [number(row.get('record_id')) for row in rows]
    if len(rows) != total or None in ids or len(set(ids)) != total:
        raise RuntimeError('Catalogue changed or has duplicate/invalid IDs; refresh the cache and retry')
    print(f'Index verified: {total} quests. Reading details with two paced workers.', flush=True)

    def load(row):
        quest_id = row['record_id']
        detail = fetch(f'/api/data/node/quest/{quest_id}', f'quest-{quest_id}', True)
        return quest_id, normalize(row, detail)

    records = {}
    with concurrent.futures.ThreadPoolExecutor(max_workers=2) as executor:
        for quest_id, record in executor.map(load, rows):
            records[quest_id] = record
            if len(records) % 100 == 0:
                print(f'Details: {len(records)}/{total}', flush=True)
    date = datetime.date.today().isoformat()
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(generate(records, date))
    summary = {'source': BASE, 'captured': date, 'count': total,
               'minimum_levels': sum('minLevel' in r for r in records.values()),
               'factions': sum('side' in r for r in records.values()),
               'zone_maps': sum(bool(r.get('mapID')) for r in records.values()),
               'npc_locations': 0, 'verified_prerequisite_links': 0}
    args.output.with_suffix('.json').write_text(json.dumps(summary, indent=2) + '\n')
    print(json.dumps(summary), flush=True)


if __name__ == '__main__':
    main()
