"""Losslessly store nested data fields as inert strings, decoded only on access.

This compiler runs outside WoW. The Lua decoder has no loadstring or remote
input: it only reads this generated, versioned database. Metadata stays eager.
"""
import argparse
import math
from pathlib import Path

from import_travel_network import encode

ROOT = Path(__file__).resolve().parents[1]


class Packer:
    def __init__(self):
        self.strings, self.indices = [], {}

    def pack(self, value):
        if isinstance(value, bool):
            return 'y' if value else 'f'
        if isinstance(value, (int, float)):
            if not math.isfinite(value):
                raise ValueError('Nonfinite packed data')
            return 'n' + str(value) + ';'
        if isinstance(value, str):
            if value not in self.indices:
                self.strings.append(value)
                self.indices[value] = len(self.strings)
            return 's' + str(self.indices[value]) + ';'
        if isinstance(value, list):
            return 'a' + str(len(value)) + ';' + ''.join(self.pack(v) for v in value)
        if isinstance(value, dict):
            return 't' + str(len(value)) + ';' + ''.join(self.pack(k) + self.pack(v)
                for k, v in sorted(value.items(), key=lambda pair: str(pair[0])))
        raise ValueError('Unsupported packed value: ' + type(value).__name__)

    def records(self, name, target, rows, lazy_rows=False):
        metadata, columns = {}, {}
        for ident, row in sorted(rows.items(), key=lambda pair: str(pair[0])):
            metadata[ident] = {}
            for key, value in sorted(row.items()):
                if isinstance(value, (list, dict)):
                    columns.setdefault(key, {})[ident] = self.pack(value)
                else:
                    metadata[ident][key] = value
        packed_rows = ', ' + encode({ident: self.pack(row) for ident, row in metadata.items()}) if lazy_rows else ''
        return (target + ' = ' + ('{}' if lazy_rows else encode(metadata)) + '\n' +
            'ns.RegisterPackedData(' + encode(name) + ', ' + target + ', ' + encode(columns) + ', strings' + packed_rows + ')\n')

    def code(self, body, comment):
        return ('local addonName, ns = ...\n\n-- ' + comment + '\n' +
            '-- Lossless nested fields; generated by tools/pack_data.py.\n' +
            'local strings = ' + encode(self.strings) + '\n' + body)


def quest_code(catalogue, entities, world_checks=None, xp=None):
    packer = Packer()
    body = 'ns.catalogue = ' + encode({k: v for k, v in catalogue.items() if k != 'quests'}) + '\n'
    body += packer.records('quests', 'ns.catalogue.quests', catalogue['quests'])
    body += 'ns.questEntities = {}\n'
    for kind, rows in sorted(entities.items()):
        body += packer.records('entities-' + kind, 'ns.questEntities.' + kind, rows, lazy_rows=True)
    if world_checks is not None:
        body += 'ns.worldQuestChecks = ' + encode(world_checks) + '\n'
    if xp is not None:
        body += 'ns.xpBaseline = ' + encode(xp) + '\n'
    return packer.code(body, 'Factual dataset includes GPL-3.0 older-world adaptations; see THIRD_PARTY_NOTICES.md.')


def dungeon_code(field, name, data, comment):
    packer = Packer()
    body = 'ns.' + field + ' = ' + encode({k: v for k, v in data.items() if k != 'dungeons'}) + '\n'
    body += packer.records(name, 'ns.' + field + '.dungeons', data['dungeons'])
    return packer.code(body, comment)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--directory', type=Path, default=ROOT / 'WowTogether')
    args = parser.parse_args()
    from build_quest_dataset import own_lua
    path = args.directory / 'QuestCatalogue.lua'
    path.write_text(quest_code(own_lua(path, 'catalogue'), own_lua(path, 'questEntities'),
        own_lua(path, 'worldQuestChecks'), own_lua(path, 'xpBaseline')))
    for field, file, name, comment in (
        ('dungeonJournalData', 'DungeonJournalData.lua', 'dungeon-journal', 'Offline Forever facts; see DUNGEON_VIEWER.md.'),
        ('dungeonMapData', 'DungeonMapData.lua', 'dungeon-maps', 'Reference floor facts; native coordinates take precedence. See DUNGEON_VIEWER.md.'),
    ):
        path = args.directory / file
        path.write_text(dungeon_code(field, name, own_lua(path, field), comment))


if __name__ == '__main__':
    main()
